using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.VisualBasic.FileIO;

namespace DocumentAiProbe;

internal static class H1D4BDiagnostic
{
    static readonly string[] Classes={"FACTURA","OTRO_DOCUMENTO","NO_DOCUMENTO"};
    static readonly string[] Splits={"TRAIN","VALIDATION","TEST"};
    static readonly CultureInfo Inv=CultureInfo.InvariantCulture;

    public static int Run(string root)
    {
        var h1=Path.Combine(root,"experiments","H1D4A"); var output=Path.Combine(root,"experiments","H1D4B");
        var assets=LoadAssets(Path.Combine(h1,"assets","assets.csv")); var manifest=LoadManifest(Path.Combine(h1,"split-manifest.csv"));
        if(assets.Count!=80||manifest.Count!=80)throw new InvalidDataException("H1D4A debe contener exactamente 80 muestras.");
        if(assets.Select(x=>x.Sha).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=80)throw new InvalidDataException("Hashes duplicados en assets.");
        foreach(var r in assets){if(!manifest.TryGetValue(r.Sha,out var m))throw new InvalidDataException("Asset ausente del manifest: "+r.Sha);if(r.Label!=m.Label||r.Group!=m.Group)throw new InvalidDataException("Diferencia assets/manifest: "+r.Sha);r.Split=m.Split;}
        if(assets.GroupBy(x=>x.Group).Any(g=>g.Select(x=>x.Split).Distinct().Count()>1))throw new InvalidDataException("Leakage por GroupId.");
        if(Directory.Exists(output))throw new IOException("La salida H1D4B ya existe: "+output); Directory.CreateDirectory(output);
        var ml=new MLContext(seed:17401); var visual=ml.Model.Load(Path.Combine(h1,"visual-model.zip"),out _); var textual=ml.Model.Load(Path.Combine(h1,"textual-model.zip"),out _);
        var ve=ml.Model.CreatePredictionEngine<VisualInput,Prediction>(visual); var te=ml.Model.CreatePredictionEngine<TextInput,Prediction>(textual);
        foreach(var r in assets){r.V=ve.Predict(new VisualInput{Features=r.Features}).Probability;if(r.Label!="NO_DOCUMENTO")r.T=te.Predict(new TextInput{Text=r.Text}).Probability;r.Alpha=Alpha(r.Text);r.Tokens=Regex.Matches(r.Text,@"\b[\p{L}\p{N}]+\b").Count;}
        var validation=assets.Where(x=>x.Split=="VALIDATION").ToList();
        var vscan=Scan(validation,true);var tscan=Scan(validation.Where(x=>x.Label!="NO_DOCUMENTO").ToList(),false);
        var vsel=vscan.OrderBy(x=>x.M.FN).ThenByDescending(x=>x.M.F1).ThenByDescending(x=>x.M.Accuracy).ThenBy(x=>Math.Abs(x.Threshold-.5)).First();
        var tsel=tscan.OrderByDescending(x=>x.M.MacroF1).ThenByDescending(x=>x.M.Recall).ThenByDescending(x=>x.M.Accuracy).ThenBy(x=>Math.Abs(x.Threshold-.5)).First();
        WritePredictions(Path.Combine(output,"all-predictions.csv"),assets);
        WriteThresholds(Path.Combine(output,"threshold-analysis.csv"),vscan,tscan,vsel.Threshold,tsel.Threshold);
        var metrics=Metrics(assets,vsel.Threshold,tsel.Threshold);File.WriteAllText(Path.Combine(output,"metrics.md"),metrics,new UTF8Encoding(false));
        var train=BM(assets.Where(x=>x.Split=="TRAIN"&&x.Label!="NO_DOCUMENTO"),false,.5);var val50=BM(validation.Where(x=>x.Label!="NO_DOCUMENTO"),false,.5);var valCal=BM(validation.Where(x=>x.Label!="NO_DOCUMENTO"),false,tsel.Threshold);
        var cases=new List<string>();if(train.MacroF1<.75)cases.Add("CASO A (dominante): El modelo no aprende ni TRAIN a 0,50.");if(train.MacroF1>=.75&&val50.MacroF1+0.15<train.MacroF1)cases.Add("CASO B: Aprende TRAIN pero no generaliza.");if(valCal.MacroF1>=val50.MacroF1+.05)cases.Add("CASO C (parcial): existe separación útil en parte de los scores y calibrar mejora el resultado, pero no es el problema principal porque TRAIN también falla.");if(cases.Count==0)cases.Add("No encaja limpiamente en A/B/C; consultar métricas y distribución de scores.");
        var test=assets.Where(x=>x.Split=="TEST").ToList();var e50=End(test,.5,.5);var ecal=End(test,vsel.Threshold,tsel.Threshold);
        var summary="# H1D4B — resumen\n\n"+string.Join("\n",cases.Select(x=>"- "+x))+"\n- Threshold visual seleccionado con VALIDATION: `"+F(vsel.Threshold)+"`\n- Threshold textual seleccionado con VALIDATION: `"+F(tsel.Threshold)+"`\n- TEST end-to-end a 0,50: accuracy="+F(e50.Accuracy)+", macro F1="+F(e50.MacroF1)+"\n- TEST end-to-end calibrado: accuracy="+F(ecal.Accuracy)+", macro F1="+F(ecal.MacroF1)+"\n- Selección de thresholds sin observar TEST: Sí\n- Reentrenamiento/modelos nuevos: No\n- Conclusión: A dominante + C parcial; no hay evidencia para B porque el textual ya falla en TRAIN.\n";
        File.WriteAllText(Path.Combine(output,"resumen.md"),summary,new UTF8Encoding(false));
        Console.WriteLine($"H1D4B | VisualThreshold={F(vsel.Threshold)} | TextThreshold={F(tsel.Threshold)} | TestAccuracy050={F(e50.Accuracy)} | TestAccuracyCal={F(ecal.Accuracy)} | TestMacroF1050={F(e50.MacroF1)} | TestMacroF1Cal={F(ecal.MacroF1)}");return 0;
    }

    static List<ScanRow> Scan(List<Row> rows,bool visual){var z=new List<ScanRow>();for(var i=0;i<=1000;i++){var t=i/1000d;z.Add(new(t,BM(rows,visual,t)));}return z;}
    static BMetrics BM(IEnumerable<Row> rows,bool visual,double threshold){var a=rows.ToList();bool Actual(Row r)=>visual?r.Label!="NO_DOCUMENTO":r.Label=="FACTURA";bool Pred(Row r)=>(visual?r.V:r.T)>=threshold;return new(a.Count(x=>Actual(x)&&Pred(x)),a.Count(x=>!Actual(x)&&!Pred(x)),a.Count(x=>!Actual(x)&&Pred(x)),a.Count(x=>Actual(x)&&!Pred(x)));}
    static EResult End(List<Row> rows,double vt,double tt){var m=new int[3,3];foreach(var r in rows){var p=r.V<vt?"NO_DOCUMENTO":r.T>=tt?"FACTURA":"OTRO_DOCUMENTO";m[Array.IndexOf(Classes,r.Label),Array.IndexOf(Classes,p)]++;}var f=new double[3];var rec=new double[3];for(var c=0;c<3;c++){var tp=m[c,c];var fp=Enumerable.Range(0,3).Where(x=>x!=c).Sum(x=>m[x,c]);var fn=Enumerable.Range(0,3).Where(x=>x!=c).Sum(x=>m[c,x]);var p=D(tp,tp+fp);rec[c]=D(tp,tp+fn);f[c]=D(2*p*rec[c],p+rec[c]);}return new(m,D(Enumerable.Range(0,3).Sum(x=>m[x,x]),rows.Count),f.Average(),rec);}
    static string Metrics(List<Row> rows,double vt,double tt){var sb=new StringBuilder("# H1D4B — métricas y diagnóstico\n\n## Matrices por split a threshold 0,50\n");foreach(var s in Splits){sb.AppendLine("\n### "+s);sb.AppendLine(BinaryMd("Visual (positivo = DOCUMENTO)",BM(rows.Where(x=>x.Split==s),true,.5)));sb.AppendLine(BinaryMd("Textual (positivo = FACTURA)",BM(rows.Where(x=>x.Split==s&&x.Label!="NO_DOCUMENTO"),false,.5)));}sb.AppendLine("\n## Distribución de scores\n\n| Modelo | Split | Clase | n | mínimo | máximo | promedio | mediana |\n|---|---|---|---:|---:|---:|---:|---:|");foreach(var s in Splits)foreach(var l in Classes){var q=rows.Where(x=>x.Split==s&&x.Label==l).ToList();sb.AppendLine(Stat("Visual",s,l,q.Select(x=>(double)x.V)));if(l!="NO_DOCUMENTO")sb.AppendLine(Stat("Textual",s,l,q.Select(x=>(double)x.T)));}sb.AppendLine("\n## Calibración exclusivamente con VALIDATION\n\n- `visual-threshold-selected`: `"+F(vt)+"`\n- `textual-threshold-selected`: `"+F(tt)+"`\n- Visual: primero minimiza DOCUMENTO → NO_DOCUMENTO; luego F1 y accuracy.\n- Textual: primero maximiza macro F1; luego recall FACTURA y accuracy.\n");var test=rows.Where(x=>x.Split=="TEST").ToList();foreach(var setting in new[]{("H1D4A threshold 0,50",.5,.5),("H1D4B thresholds calibrados",vt,tt)}){sb.AppendLine("\n## TEST — "+setting.Item1);sb.AppendLine(BinaryMd("Visual",BM(test,true,setting.Item2)));sb.AppendLine(BinaryMd("Textual",BM(test.Where(x=>x.Label!="NO_DOCUMENTO"),false,setting.Item3)));var e=End(test,setting.Item2,setting.Item3);sb.AppendLine(EndMd(e));sb.AppendLine("- FACTURA → NO_DOCUMENTO: "+e.Matrix[0,2]);sb.AppendLine("- FACTURA → OTRO_DOCUMENTO: "+e.Matrix[0,1]);}sb.AppendLine("\n## Diagnóstico técnico del texto (sin contenido documental)\n\n| Split | Clase | n | TextLen prom. | Origen | alfanumérico prom. | tokens prom. | FACTURA | CUIT | IVA | CAE/CAEA | TOTAL |\n|---|---|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|");foreach(var s in Splits)foreach(var l in Classes.Take(2)){var q=rows.Where(x=>x.Split==s&&x.Label==l).ToList();sb.AppendLine($"| {s} | {l} | {q.Count} | {F(q.Average(x=>x.TextLen))} | {string.Join("; ",q.GroupBy(x=>x.TextOrigin).OrderBy(x=>x.Key).Select(x=>x.Key+"="+x.Count()))} | {F(q.Average(x=>x.Alpha))} | {F(q.Average(x=>x.Tokens))} | {q.Count(x=>Signal(x.Text,"FACTURA"))} | {q.Count(x=>Signal(x.Text,"CUIT"))} | {q.Count(x=>Signal(x.Text,"IVA"))} | {q.Count(x=>Signal(x.Text,"CAE")||Signal(x.Text,"CAEA"))} | {q.Count(x=>Signal(x.Text,"TOTAL"))} |");}return sb.ToString();}
    static string BinaryMd(string title,BMetrics m)=>"\n#### "+title+"\n\n| | Pred + | Pred - |\n|---|---:|---:|\n| Real + | "+m.TP+" | "+m.FN+" |\n| Real - | "+m.FP+" | "+m.TN+" |\n\n- Accuracy="+F(m.Accuracy)+"; F1 positivo="+F(m.F1)+"; macro F1="+F(m.MacroF1)+"; recall positivo="+F(m.Recall)+"\n";
    static string EndMd(EResult e){var sb=new StringBuilder("\n### Matriz end-to-end 3×3\n\n| real/pred | FACTURA | OTRO_DOCUMENTO | NO_DOCUMENTO |\n|---|---:|---:|---:|\n");for(var i=0;i<3;i++)sb.AppendLine($"| {Classes[i]} | {e.Matrix[i,0]} | {e.Matrix[i,1]} | {e.Matrix[i,2]} |");sb.AppendLine("\n- Accuracy: "+F(e.Accuracy));sb.AppendLine("- Macro F1: "+F(e.MacroF1));for(var i=0;i<3;i++)sb.AppendLine("- Recall "+Classes[i]+": "+F(e.Recall[i]));return sb.ToString();}
    static string Stat(string model,string split,string label,IEnumerable<double> source){var q=source.OrderBy(x=>x).ToList();var med=q.Count%2==1?q[q.Count/2]:(q[q.Count/2-1]+q[q.Count/2])/2;return $"| {model} | {split} | {label} | {q.Count} | {F(q.Min())} | {F(q.Max())} | {F(q.Average())} | {F(med)} |";}
    static void WritePredictions(string path,List<Row> rows){var lines=new List<string>{"filename,GroupId,Label,Split,VisualProbability,VisualPrediction_050,TextProbability,TextPrediction_050,TextLen,TextOrigin,SourceType,AlphaNumericPercent,TokenCount,HasFACTURA,HasCUIT,HasIVA,HasCAEorCAEA,HasTOTAL"};foreach(var r in rows)lines.Add(string.Join(",",new[]{Path.GetFileName(r.Path),r.Group,r.Label,r.Split,F(r.V),r.V>=.5?"DOCUMENTO":"NO_DOCUMENTO",r.Label=="NO_DOCUMENTO"?"":F(r.T),r.Label=="NO_DOCUMENTO"?"":r.T>=.5?"FACTURA":"OTRO_DOCUMENTO",r.TextLen.ToString(Inv),r.TextOrigin,r.SourceType,F(r.Alpha),r.Tokens.ToString(Inv),B(Signal(r.Text,"FACTURA")),B(Signal(r.Text,"CUIT")),B(Signal(r.Text,"IVA")),B(Signal(r.Text,"CAE")||Signal(r.Text,"CAEA")),B(Signal(r.Text,"TOTAL"))}.Select(Csv)));File.WriteAllLines(path,lines,new UTF8Encoding(false));}
    static void WriteThresholds(string path,List<ScanRow> v,List<ScanRow> t,double vs,double ts){var lines=new List<string>{"Model,Threshold,TP,TN,FP,FN,Accuracy,PrecisionPositive,RecallPositive,F1Positive,MacroF1,Selected"};foreach(var x in v.Select(x=>("VISUAL",x,vs)).Concat(t.Select(x=>("TEXTUAL",x,ts))))lines.Add(string.Join(",",new[]{x.Item1,F(x.x.Threshold),x.x.M.TP.ToString(),x.x.M.TN.ToString(),x.x.M.FP.ToString(),x.x.M.FN.ToString(),F(x.x.M.Accuracy),F(x.x.M.Precision),F(x.x.M.Recall),F(x.x.M.F1),F(x.x.M.MacroF1),B(Math.Abs(x.x.Threshold-x.Item3)<1e-9)}));File.WriteAllLines(path,lines,new UTF8Encoding(false));}
    static List<Row> LoadAssets(string path){var z=new List<Row>();foreach(var v in CsvRows(path)){z.Add(new(){Path=v["Path"],Label=v["Label"],Group=v["GroupId"],SourceType=v["SourceType"],Sha=v["Sha256"],Features=v["VisualFeatures"].Split(';').Select(x=>float.Parse(x,Inv)).ToArray(),Text=Encoding.UTF8.GetString(Convert.FromBase64String(v["TextBase64"])),TextOrigin=v["TextOrigin"],TextLen=int.Parse(v["TextLen"],Inv)});}return z;}
    static Dictionary<string,MRow> LoadManifest(string path)=>CsvRows(path).Select(v=>new MRow(v["Sha256"],v["Label"],v["GroupId"],v["Split"])).ToDictionary(x=>x.Sha,StringComparer.OrdinalIgnoreCase);
    static IEnumerable<Dictionary<string,string>> CsvRows(string path){using var p=new TextFieldParser(path){TextFieldType=FieldType.Delimited,HasFieldsEnclosedInQuotes=true};p.SetDelimiters(",");var h=p.ReadFields()??throw new InvalidDataException("CSV sin header");while(!p.EndOfData){var f=p.ReadFields();if(f!=null)yield return h.Select((n,i)=>(n,i)).ToDictionary(x=>x.n,x=>x.i<f.Length?f[x.i]:"",StringComparer.OrdinalIgnoreCase);}}
    static double Alpha(string s)=>s.Length==0?0:100d*s.Count(char.IsLetterOrDigit)/s.Length;static bool Signal(string text,string word)=>Regex.IsMatch(text,@"\b"+Regex.Escape(word)+@"\b",RegexOptions.IgnoreCase|RegexOptions.CultureInvariant);static string Csv(string s)=>"\""+(s??"").Replace("\"","\"\"")+"\"";static string F(double x)=>x.ToString("0.000000",Inv);static string B(bool x)=>x?"true":"false";static double D(double a,double b)=>b==0?0:a/b;
    sealed class Row{public string Path="",Label="",Group="",SourceType="",Sha="",Split="",Text="",TextOrigin="";public float[] Features=Array.Empty<float>();public int TextLen,Tokens;public double V,T,Alpha;}
    sealed record MRow(string Sha,string Label,string Group,string Split);sealed record ScanRow(double Threshold,BMetrics M);sealed record EResult(int[,] Matrix,double Accuracy,double MacroF1,double[] Recall);
    sealed class VisualInput{[VectorType(64)]public float[] Features{get;set;}=Array.Empty<float>();public bool Label{get;set;}}sealed class TextInput{public string Text{get;set;}="";public bool Label{get;set;}}sealed class Prediction{[ColumnName("PredictedLabel")]public bool PredictedLabel{get;set;}public float Probability{get;set;}public float Score{get;set;}}
    sealed class BMetrics{public BMetrics(int tp,int tn,int fp,int fn){TP=tp;TN=tn;FP=fp;FN=fn;}public int TP,TN,FP,FN;public double Accuracy=>D(TP+TN,TP+TN+FP+FN);public double Precision=>D(TP,TP+FP);public double Recall=>D(TP,TP+FN);public double F1=>D(2*Precision*Recall,Precision+Recall);public double NegativeF1{get{var p=D(TN,TN+FN);var r=D(TN,TN+FP);return D(2*p*r,p+r);}}public double MacroF1=>(F1+NegativeF1)/2;}
}
