using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Transforms.Text;
using Microsoft.VisualBasic.FileIO;

namespace DocumentAiProbe;

internal static class H1D4CExperiment
{
    const int Folds=5; static readonly CultureInfo Inv=CultureInfo.InvariantCulture; static readonly string[] Names={"A_BASELINE","B_WORD_NGRAMS","C_WORD_CHAR_NGRAMS","D_HYBRID_FISCAL"};static readonly string[] Classes={"FACTURA","OTRO_DOCUMENTO","NO_DOCUMENTO"};
    public static int Run(string root)
    {
        var h1=Path.Combine(root,"experiments","H1D4A");var output=Path.Combine(root,"experiments","H1D4C");if(Directory.Exists(output))throw new IOException("La salida H1D4C ya existe: "+output);
        var rows=Load(Path.Combine(h1,"assets","assets.csv"));var manifest=Manifest(Path.Combine(h1,"split-manifest.csv"));foreach(var r in rows){if(!manifest.TryGetValue(r.Sha,out var m))throw new InvalidDataException("Falta hash en manifest.");r.Split=m.Split;if(r.Label!=m.Label||r.Group!=m.Group)throw new InvalidDataException("Assets y manifest difieren.");}
        if(rows.Count!=80||rows.Select(x=>x.Sha).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=80||rows.GroupBy(x=>x.Group).Any(g=>g.Select(x=>x.Split).Distinct().Count()>1))throw new InvalidDataException("Integridad H1D4A inválida.");
        var development=rows.Where(x=>x.Split is "TRAIN" or "VALIDATION"&&x.Label!="NO_DOCUMENTO").ToList();AssignFolds(development);AuditFolds(development);Directory.CreateDirectory(output);
        var cv=new List<CvResult>();var predictions=new List<PredRow>();
        foreach(var name in Names){for(var fold=0;fold<Folds;fold++){var ml=new MLContext(seed:17401+fold);var train=development.Where(x=>x.Fold!=fold).Select(Input).ToList();var valid=development.Where(x=>x.Fold==fold).ToList();var data=ml.Data.LoadFromEnumerable(train);var model=Pipeline(ml,name).Fit(data);var engine=ml.Model.CreatePredictionEngine<TextInput,Prediction>(model);foreach(var r in valid){var p=engine.Predict(Input(r));predictions.Add(new(name,fold,r,p.Probability,p.PredictedLabel));}}var own=predictions.Where(x=>x.Variant==name).ToList();cv.Add(new(name,Metrics(own.Select(x=>(x.Row.Label=="FACTURA",x.Predicted)))));}
        var winner=cv.OrderByDescending(x=>x.M.Recall).ThenByDescending(x=>x.M.MacroF1).ThenBy(x=>x.M.FN).ThenByDescending(x=>x.M.Accuracy).First();
        var finalMl=new MLContext(seed:17401);var finalData=finalMl.Data.LoadFromEnumerable(development.Select(Input));var finalModel=Pipeline(finalMl,winner.Name).Fit(finalData);var modelPath=Path.Combine(output,"textual-model.zip");finalMl.Model.Save(finalModel,finalData.Schema,modelPath);var finalEngine=finalMl.Model.CreatePredictionEngine<TextInput,Prediction>(finalModel);
        var test=rows.Where(x=>x.Split=="TEST"&&x.Label!="NO_DOCUMENTO").ToList();var testPred=test.Select(r=>new PredRow(winner.Name,-1,r,finalEngine.Predict(Input(r)).Probability,finalEngine.Predict(Input(r)).PredictedLabel)).ToList();var testM=Metrics(testPred.Select(x=>(x.Row.Label=="FACTURA",x.Predicted)));
        var visualModel=finalMl.Model.Load(Path.Combine(h1,"visual-model.zip"),out _);var ve=finalMl.Model.CreatePredictionEngine<VisualInput,Prediction>(visualModel);var allTest=rows.Where(x=>x.Split=="TEST").ToList();var matrix=new int[3,3];var details=new List<TestRow>();foreach(var r in allTest){var vp=ve.Predict(new VisualInput{Features=r.Features}).Probability;double? tp=null;string pred;if(vp<.726)pred="NO_DOCUMENTO";else{tp=finalEngine.Predict(Input(r)).Probability;pred=tp>=.5?"FACTURA":"OTRO_DOCUMENTO";}matrix[Array.IndexOf(Classes,r.Label),Array.IndexOf(Classes,pred)]++;details.Add(new(r,pred,vp,tp));}
        var end=End(matrix,allTest.Count);WriteCv(Path.Combine(output,"cv-results.csv"),cv,predictions);WriteTest(Path.Combine(output,"test-predictions.csv"),details);WriteMetrics(Path.Combine(output,"metrics.md"),development,cv,winner,testM,matrix,end);WriteSummary(Path.Combine(output,"resumen.md"),winner,testM,matrix,end,modelPath);
        Console.WriteLine($"H1D4C | Winner={winner.Name} | CVFacturaRecall={F(winner.M.Recall)} | CVMacroF1={F(winner.M.MacroF1)} | TestFacturaRecall={F(testM.Recall)} | TestMacroF1={F(testM.MacroF1)} | EndMacroF1={F(end.MacroF1)} | FacturaAOtro={matrix[0,1]} | FacturaANo={matrix[0,2]}");return 0;
    }
    static IEstimator<ITransformer> Pipeline(MLContext ml,string name){var trainer=ml.BinaryClassification.Trainers.SdcaLogisticRegression(labelColumnName:"Label",featureColumnName:"Features",maximumNumberOfIterations:200);if(name=="A_BASELINE")return ml.Transforms.Text.FeaturizeText("Features",nameof(TextInput.Text)).Append(trainer);var word=new WordBagEstimator.Options{NgramLength=2,UseAllLengths=true,MaximumNgramsCount=new[]{20000}};var options=new TextFeaturizingEstimator.Options{CaseMode=TextNormalizingEstimator.CaseMode.Lower,KeepDiacritics=false,KeepPunctuations=false,KeepNumbers=true,Norm=TextFeaturizingEstimator.NormFunction.L2,WordFeatureExtractor=word,CharFeatureExtractor=name=="C_WORD_CHAR_NGRAMS"?new WordBagEstimator.Options{NgramLength=3,UseAllLengths=false,MaximumNgramsCount=new[]{30000}}:null};var text=ml.Transforms.Text.FeaturizeText("TextFeatures",options,nameof(TextInput.Text));if(name=="D_HYBRID_FISCAL")return text.Append(ml.Transforms.NormalizeMinMax("FiscalNormalized",nameof(TextInput.FiscalFeatures))).Append(ml.Transforms.Concatenate("Features","TextFeatures","FiscalNormalized")).Append(trainer);return text.Append(ml.Transforms.CopyColumns("Features","TextFeatures")).Append(trainer);}
    static TextInput Input(Row r)=>new(){Text=r.Text,Label=r.Label=="FACTURA",FiscalFeatures=Fiscal(r.Text)};
    static float[] Fiscal(string s){float Count(string p)=>Regex.Matches(s,p,RegexOptions.IgnoreCase|RegexOptions.CultureInvariant).Count;return new[]{Count(@"\bFACTURA\b"),Count(@"\bCUIT\b"),Count(@"\bIVA\b"),Count(@"\bCAE(?:A)?\b"),Count(@"\bTOTAL\b"),Count(@"PUNTO\s+DE\s+VENTA|PTO\.?\s*VTA"),Count(@"COMPROBANTE"),Count(@"\$\s*\d|\d+[.,]\d{2}\b"),Count(@"\b\d{2}-?\d{8}-?\d\b"),Count(@"RESPONSABLE\s+INSCRIPTO|MONOTRIBUTO"),Count(@"PERCEPCI[ÓO]N|RETENCI[ÓO]N"),MathF.Log(1+s.Length)};}
    static void AssignFolds(List<Row> rows){foreach(var label in new[]{"FACTURA","OTRO_DOCUMENTO"}){var groups=rows.Where(x=>x.Label==label).Select(x=>x.Group).Distinct().OrderBy(x=>Key(label+"|"+x)).ToList();for(var i=0;i<groups.Count;i++)foreach(var r in rows.Where(x=>x.Group==groups[i]))r.Fold=i%Folds;}}
    static void AuditFolds(List<Row> rows){if(rows.GroupBy(x=>x.Group).Any(g=>g.Select(x=>x.Fold).Distinct().Count()>1))throw new InvalidDataException("GroupId dividido entre folds.");for(var i=0;i<Folds;i++)foreach(var l in new[]{"FACTURA","OTRO_DOCUMENTO"})if(!rows.Any(x=>x.Fold==i&&x.Label==l))throw new InvalidDataException($"Fold {i} sin {l}.");}
    static BMetrics Metrics(IEnumerable<(bool Actual,bool Pred)> q){var a=q.ToList();return new(a.Count(x=>x.Actual&&x.Pred),a.Count(x=>!x.Actual&&!x.Pred),a.Count(x=>!x.Actual&&x.Pred),a.Count(x=>x.Actual&&!x.Pred));}
    static EResult End(int[,]m,int n){var recall=new double[3];var f=new double[3];for(var c=0;c<3;c++){var tp=m[c,c];var fp=Enumerable.Range(0,3).Where(x=>x!=c).Sum(x=>m[x,c]);var fn=Enumerable.Range(0,3).Where(x=>x!=c).Sum(x=>m[c,x]);var p=D(tp,tp+fp);recall[c]=D(tp,tp+fn);f[c]=D(2*p*recall[c],p+recall[c]);}return new(D(Enumerable.Range(0,3).Sum(x=>m[x,x]),n),f.Average(),recall);}
    static void WriteCv(string path,List<CvResult> cv,List<PredRow> p){var l=new List<string>{"RecordType,Variant,Fold,Filename,GroupId,Label,Probability,Prediction,Accuracy,FacturaPrecision,FacturaRecall,FacturaF1,OtroPrecision,OtroRecall,OtroF1,MacroF1,TP,TN,FP,FN"};foreach(var x in cv){var m=x.M;l.Add(string.Join(",",new[]{"SUMMARY",x.Name,"","","","","","",F(m.Accuracy),F(m.Precision),F(m.Recall),F(m.F1),F(m.NegPrecision),F(m.NegRecall),F(m.NegF1),F(m.MacroF1),m.TP.ToString(),m.TN.ToString(),m.FP.ToString(),m.FN.ToString()}.Select(Csv)));}foreach(var x in p)l.Add(string.Join(",",new[]{"OOF",x.Variant,x.Fold.ToString(),Path.GetFileName(x.Row.Path),x.Row.Group,x.Row.Label,F(x.Probability),x.Predicted?"FACTURA":"OTRO_DOCUMENTO","","","","","","","","","","","",""}.Select(Csv)));File.WriteAllLines(path,l,new UTF8Encoding(false));}
    static void WriteTest(string path,List<TestRow> rows){var l=new List<string>{"filename,GroupId,Label,VisualProbability,TextProbability,Prediction"};l.AddRange(rows.Select(x=>string.Join(",",new[]{Path.GetFileName(x.Row.Path),x.Row.Group,x.Row.Label,F(x.Visual),x.Text.HasValue?F(x.Text.Value):"",x.Prediction}.Select(Csv))));File.WriteAllLines(path,l,new UTF8Encoding(false));}
    static void WriteMetrics(string path,List<Row> dev,List<CvResult> cv,CvResult winner,BMetrics test,int[,] matrix,EResult end){var sb=new StringBuilder("# H1D4C — evaluación textual group-aware\n\n- Desarrollo: TRAIN+VALIDATION H1D4A, "+dev.Count+" archivos, "+dev.Select(x=>x.Group).Distinct().Count()+" grupos.\n- Folds: 5, estratificados por clase y atómicos por GroupId.\n- Selección: sólo predicciones out-of-fold; TEST no intervino.\n\n## Métricas CV agregadas\n\n| Variante | Accuracy | P Factura | R Factura | F1 Factura | P Otro | R Otro | F1 Otro | Macro F1 | Matriz TP/TN/FP/FN |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---|\n");foreach(var x in cv){var m=x.M;sb.AppendLine($"| {x.Name} | {F(m.Accuracy)} | {F(m.Precision)} | {F(m.Recall)} | {F(m.F1)} | {F(m.NegPrecision)} | {F(m.NegRecall)} | {F(m.NegF1)} | {F(m.MacroF1)} | {m.TP}/{m.TN}/{m.FP}/{m.FN} |");}sb.AppendLine("\n## Ganador\n\n`"+winner.Name+"`, elegido primero por recall FACTURA, luego macro F1, FN y accuracy.\n\n## Condición de parada\n\nNinguna variante aprendió razonablemente en evaluación group-aware. Se detiene sin recolectar datos.\n\n## TEST H1D4A — regresión experimental\n\nEste TEST ya fue observado en H1D4A/H1D4B; no constituye certificación final independiente.\n\n"+BinaryMd(test)+"\nH1D4A: recall FACTURA 0, macro F1 0,250000. H1D4B calibrado: recall FACTURA 0,166667, macro F1 0,415584. H1D4C no mejora H1D4B.\n\n## Integración temporal con visual H1D4B (threshold 0,726)\n\n"+MatrixMd(matrix,end)+"\n\n## Conclusión técnica\n\nLas representaciones probadas no generalizan suficientemente entre GroupId; no reemplazar el modelo existente ni integrar en producto.\n");File.WriteAllText(path,sb.ToString(),new UTF8Encoding(false));}
    static void WriteSummary(string path,CvResult w,BMetrics test,int[,]m,EResult e,string model){var s="# H1D4C — resumen ejecutivo\n\n- Variantes: baseline; word n-grams; word+character n-grams; híbrida word n-grams+señales fiscales aprendidas.\n- Ganador CV: `"+w.Name+"`; recall FACTURA="+F(w.M.Recall)+", macro F1="+F(w.M.MacroF1)+".\n- TEST textual: recall FACTURA="+F(test.Recall)+", macro F1="+F(test.MacroF1)+", FACTURA→OTRO_DOCUMENTO="+test.FN+".\n- End-to-end: macro F1="+F(e.MacroF1)+", recall FACTURA="+F(e.Recall[0])+", FACTURA→OTRO_DOCUMENTO="+m[0,1]+", FACTURA→NO_DOCUMENTO="+m[0,2]+".\n- Modelo experimental: `"+model+"`; no reemplaza H1D4A ni producto.\n- TEST previamente observado: regresión experimental, no certificación independiente.\n- Comparación: H1D4A recall FACTURA 0/macro F1 0,250000; H1D4B calibrado recall 0,166667/macro F1 0,415584.\n- Condición de parada: ninguna variante aprendió razonablemente en CV group-aware; no recolectar datos ni integrar en producto.\n";File.WriteAllText(path,s,new UTF8Encoding(false));}
    static string BinaryMd(BMetrics m)=>$"| | Pred FACTURA | Pred OTRO |\n|---|---:|---:|\n| Real FACTURA | {m.TP} | {m.FN} |\n| Real OTRO | {m.FP} | {m.TN} |\n\n- Accuracy={F(m.Accuracy)}; recall FACTURA={F(m.Recall)}; F1 FACTURA={F(m.F1)}; recall OTRO={F(m.NegRecall)}; F1 OTRO={F(m.NegF1)}; macro F1={F(m.MacroF1)}\n";
    static string MatrixMd(int[,]m,EResult e){var sb=new StringBuilder("| real/pred | FACTURA | OTRO_DOCUMENTO | NO_DOCUMENTO |\n|---|---:|---:|---:|\n");for(var i=0;i<3;i++)sb.AppendLine($"| {Classes[i]} | {m[i,0]} | {m[i,1]} | {m[i,2]} |");sb.AppendLine($"\n- Accuracy={F(e.Accuracy)}; macro F1={F(e.MacroF1)}; recall FACTURA={F(e.Recall[0])}; recall OTRO_DOCUMENTO={F(e.Recall[1])}; recall NO_DOCUMENTO={F(e.Recall[2])}\n- FACTURA→OTRO_DOCUMENTO={m[0,1]}; FACTURA→NO_DOCUMENTO={m[0,2]}");return sb.ToString();}
    static List<Row> Load(string path){var z=new List<Row>();foreach(var v in CsvRows(path))z.Add(new(){Path=v["Path"],Label=v["Label"],Group=v["GroupId"],Sha=v["Sha256"],Text=Encoding.UTF8.GetString(Convert.FromBase64String(v["TextBase64"])),Features=v["VisualFeatures"].Split(';').Select(x=>float.Parse(x,Inv)).ToArray()});return z;}
    static Dictionary<string,MRow> Manifest(string path)=>CsvRows(path).Select(v=>new MRow(v["Sha256"],v["Label"],v["GroupId"],v["Split"])).ToDictionary(x=>x.Sha,StringComparer.OrdinalIgnoreCase);static IEnumerable<Dictionary<string,string>> CsvRows(string path){using var p=new TextFieldParser(path){TextFieldType=FieldType.Delimited,HasFieldsEnclosedInQuotes=true};p.SetDelimiters(",");var h=p.ReadFields()!;while(!p.EndOfData){var f=p.ReadFields();if(f!=null)yield return h.Select((n,i)=>(n,i)).ToDictionary(x=>x.n,x=>x.i<f.Length?f[x.i]:"",StringComparer.OrdinalIgnoreCase);}}
    static string Key(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes("H1D4C-fold-v1|"+s)));static string Csv(string s)=>"\""+(s??"").Replace("\"","\"\"")+"\"";static string F(double x)=>x.ToString("0.000000",Inv);static double D(double a,double b)=>b==0?0:a/b;
    sealed class Row{public string Path="",Label="",Group="",Sha="",Split="",Text="";public int Fold;public float[] Features=Array.Empty<float>();}sealed record MRow(string Sha,string Label,string Group,string Split);sealed record CvResult(string Name,BMetrics M);sealed record PredRow(string Variant,int Fold,Row Row,double Probability,bool Predicted);sealed record TestRow(Row Row,string Prediction,double Visual,double? Text);sealed record EResult(double Accuracy,double MacroF1,double[] Recall);
    sealed class TextInput{public string Text{get;set;}="";public bool Label{get;set;}[VectorType(12)]public float[] FiscalFeatures{get;set;}=Array.Empty<float>();}sealed class VisualInput{[VectorType(64)]public float[] Features{get;set;}=Array.Empty<float>();public bool Label{get;set;}}sealed class Prediction{[ColumnName("PredictedLabel")]public bool PredictedLabel{get;set;}public float Probability{get;set;}public float Score{get;set;}}
    sealed class BMetrics{public BMetrics(int tp,int tn,int fp,int fn){TP=tp;TN=tn;FP=fp;FN=fn;}public int TP,TN,FP,FN;public double Accuracy=>D(TP+TN,TP+TN+FP+FN);public double Precision=>D(TP,TP+FP);public double Recall=>D(TP,TP+FN);public double F1=>D(2*Precision*Recall,Precision+Recall);public double NegPrecision=>D(TN,TN+FN);public double NegRecall=>D(TN,TN+FP);public double NegF1=>D(2*NegPrecision*NegRecall,NegPrecision+NegRecall);public double MacroF1=>(F1+NegF1)/2;}
}
