<%@ Page Title="Bandeja Gmail" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" Async="true" AsyncTimeout="600" CodeBehind="Gmail_Bandeja.aspx.cs" Inherits="RecepcionDocumental.Gmail_Bandeja" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server"><main>
<header class="page-header d-flex justify-content-between align-items-end"><div><p class="eyebrow">Gmail</p><h1>Bandeja de entrada</h1></div><div><asp:Button ID="btnBuscar" runat="server" Text="Buscar nuevos correos" CssClass="btn btn-primary me-2" UseSubmitBehavior="false" OnClientClick="this.disabled=true;this.value='Buscando…';" OnClick="Buscar_Click" /><a href="Gmail_Config.aspx" class="btn btn-outline-primary">Configurar cuenta</a></div></header>
<asp:Panel ID="pnlDatabaseWarning" runat="server" Visible="false" CssClass="alert alert-warning"><asp:Literal ID="litDatabaseWarning" runat="server" /></asp:Panel>
<asp:Panel ID="pnlSinCuenta" runat="server" Visible="false" CssClass="alert alert-info">No hay una cuenta Gmail activa. <a href="Gmail_Config.aspx">Configurar cuenta</a>.</asp:Panel>
<asp:Panel ID="pnlResultado" runat="server" Visible="false" CssClass="alert alert-success"><h2 class="h5">Sincronización terminada</h2><ul class="mb-0"><li>Mensajes encontrados: <asp:Literal ID="litEncontrados" runat="server" /></li><li>Mensajes nuevos: <asp:Literal ID="litNuevos" runat="server" /></li><li>Adjuntos descargados: <asp:Literal ID="litDescargados" runat="server" /></li><li>Adjuntos ya existentes: <asp:Literal ID="litExistentes" runat="server" /></li><li>Errores: <asp:Literal ID="litErrores" runat="server" /></li></ul><asp:Literal ID="litFallback" runat="server" /></asp:Panel>
<asp:Panel ID="pnlSinMensajes" runat="server" CssClass="empty-state"><h2>Todavía no se recibieron mensajes desde Gmail.</h2><p class="text-secondary mb-0">Usá “Buscar nuevos correos” para iniciar la recepción.</p></asp:Panel>
<asp:Panel ID="pnlTabla" runat="server" Visible="false" CssClass="table-responsive"><asp:Repeater ID="rptMensajes" runat="server"><HeaderTemplate><table class="table table-hover align-middle"><thead><tr><th>Fecha UTC</th><th>Remitente</th><th>Asunto</th><th>Adjuntos</th><th>Estado</th><th></th></tr></thead><tbody></HeaderTemplate><ItemTemplate><tr><td><%#: Eval("FechaMensajeUtc", "{0:dd/MM/yyyy HH:mm}") %></td><td><%#: Eval("Remitente") %></td><td><%#: Eval("Asunto") %></td><td><%#: Eval("CantidadAdjuntos") %></td><td><%#: Eval("Estado") %></td><td><a href='<%# "Gmail_Mensaje_Ver.aspx?id=" + Eval("Id") %>'>Ver</a></td></tr></ItemTemplate><FooterTemplate></tbody></table></FooterTemplate></asp:Repeater></asp:Panel>
</main></asp:Content>
