<%@ Page Title="Detalle de mensaje" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Gmail_Mensaje_Ver.aspx.cs" Inherits="RecepcionDocumental.Gmail_Mensaje_Ver" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server"><main><header class="page-header"><p class="eyebrow">Gmail</p><h1>Detalle del mensaje</h1></header>
<asp:Panel ID="pnlAviso" runat="server" CssClass="alert alert-info"><asp:Literal ID="litAviso" runat="server" /></asp:Panel>
<asp:Panel ID="pnlMensaje" runat="server" Visible="false"><div class="card"><div class="card-body"><h2 class="h4"><asp:Literal ID="litAsunto" runat="server" /></h2><dl class="row detail-list mt-4"><dt class="col-sm-3">Remitente</dt><dd class="col-sm-9"><asp:Literal ID="litRemitente" runat="server" /></dd><dt class="col-sm-3">Cuenta</dt><dd class="col-sm-9"><asp:Literal ID="litCuenta" runat="server" /></dd><dt class="col-sm-3">Fecha UTC</dt><dd class="col-sm-9"><asp:Literal ID="litFecha" runat="server" /></dd><dt class="col-sm-3">ID Gmail</dt><dd class="col-sm-9"><asp:Literal ID="litGmailId" runat="server" /></dd><dt class="col-sm-3">Resumen</dt><dd class="col-sm-9"><asp:Literal ID="litSnippet" runat="server" /></dd></dl></div></div>
<h2 class="h5 mt-4"><asp:Literal ID="litItemsTitle" runat="server" /></h2>
<asp:Panel ID="pnlSinAdjuntos" runat="server" CssClass="text-secondary">No hay adjuntos registrados.</asp:Panel>
<asp:Panel ID="pnlDocumentos" runat="server" Visible="false"><asp:Repeater ID="rptDocumentos" runat="server"><HeaderTemplate><div class="table-responsive"><table class="table"><thead><tr><th>Nombre</th><th>Clasificación automática</th><th>Resultado revisión</th><th>Método</th><th>Confianza</th><th>Origen</th><th>Ruta interna</th></tr></thead><tbody></HeaderTemplate><ItemTemplate><tr><td><%#: Eval("NombreOriginal") %></td><td><%#: Eval("Clasificacion") %></td><td><%#: Eval("ResultadoRevision") ?? "Pendiente" %></td><td><%#: Eval("MetodoDeteccion") %></td><td><%#: FormatConfidence(Eval("Confianza")) %></td><td><%#: Eval("OrigenTipo") %></td><td><%#: Eval("RutaInternaContenedor") %></td></tr></ItemTemplate><FooterTemplate></tbody></table></div></FooterTemplate></asp:Repeater></asp:Panel>
<asp:Panel ID="pnlAdjuntosHistoricos" runat="server" Visible="false"><asp:Repeater ID="rptAdjuntos" runat="server"><HeaderTemplate><div class="table-responsive"><table class="table"><thead><tr><th>Nombre</th><th>MIME</th><th>Tamaño</th><th>Estado</th><th>Descarga UTC</th></tr></thead><tbody></HeaderTemplate><ItemTemplate><tr><td><%#: Eval("NombreOriginal") %></td><td><%#: Eval("MimeType") %></td><td><%#: FormatSize(Eval("TamanioBytes")) %></td><td><%#: Eval("Estado") %></td><td><%#: Eval("FechaDescargaUtc", "{0:dd/MM/yyyy HH:mm}") %></td></tr></ItemTemplate><FooterTemplate></tbody></table></div></FooterTemplate></asp:Repeater></asp:Panel></asp:Panel><p class="mt-3"><a href="Gmail_Bandeja.aspx">← Volver a la bandeja</a></p>
</main></asp:Content>
