//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepcionDocumental
{
    public partial class Logout
    {
    }
}
