USE [RecepcionDocumental];
GO
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID(N'dbo.GmailCuenta', N'U') IS NULL
BEGIN
 CREATE TABLE dbo.GmailCuenta (Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GmailCuenta PRIMARY KEY, Email NVARCHAR(320) NOT NULL, Activo BIT NOT NULL CONSTRAINT DF_GmailCuenta_Activo DEFAULT (1), RefreshTokenProtegido VARBINARY(MAX) NULL, UltimaConsultaUtc DATETIME2(0) NULL, FechaAlta DATETIME2(0) NOT NULL CONSTRAINT DF_GmailCuenta_FechaAlta DEFAULT (SYSUTCDATETIME()), FechaModificacion DATETIME2(0) NOT NULL CONSTRAINT DF_GmailCuenta_FechaModificacion DEFAULT (SYSUTCDATETIME()));
END;
IF OBJECT_ID(N'dbo.GmailMensaje', N'U') IS NULL
BEGIN
 CREATE TABLE dbo.GmailMensaje (Id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GmailMensaje PRIMARY KEY, GmailCuentaId INT NOT NULL, GmailMessageId NVARCHAR(255) NOT NULL, GmailThreadId NVARCHAR(255) NULL, FechaMensajeUtc DATETIME2(0) NOT NULL, Remitente NVARCHAR(500) NOT NULL, Asunto NVARCHAR(1000) NULL, Snippet NVARCHAR(2000) NULL, FechaDetectadoUtc DATETIME2(0) NOT NULL CONSTRAINT DF_GmailMensaje_FechaDetectado DEFAULT (SYSUTCDATETIME()), CONSTRAINT FK_GmailMensaje_GmailCuenta FOREIGN KEY (GmailCuentaId) REFERENCES dbo.GmailCuenta(Id), CONSTRAINT UQ_GmailMensaje_Cuenta_MessageId UNIQUE (GmailCuentaId, GmailMessageId));
END;
IF OBJECT_ID(N'dbo.GmailAdjunto', N'U') IS NULL
BEGIN
 CREATE TABLE dbo.GmailAdjunto (Id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GmailAdjunto PRIMARY KEY, GmailMensajeId BIGINT NOT NULL, GmailAttachmentId NVARCHAR(255) NULL, GmailPartId NVARCHAR(255) NULL, NombreOriginal NVARCHAR(500) NOT NULL, MimeType NVARCHAR(255) NULL, TamanioBytes BIGINT NULL, RutaLocal NVARCHAR(2000) NULL, HashSha256 CHAR(64) NULL, FechaDescargaUtc DATETIME2(0) NULL, Estado NVARCHAR(50) NOT NULL CONSTRAINT DF_GmailAdjunto_Estado DEFAULT (N'Pendiente'), CONSTRAINT FK_GmailAdjunto_GmailMensaje FOREIGN KEY (GmailMensajeId) REFERENCES dbo.GmailMensaje(Id), CONSTRAINT CK_GmailAdjunto_TamanioBytes CHECK (TamanioBytes IS NULL OR TamanioBytes >= 0));
END;
COMMIT TRANSACTION;
GO
