using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.VisualBasic.FileIO;
using PDFtoImage;

namespace PdfRasterProbe
{
 internal static class H1D7BVisualShadowProbe
 {
  const double Threshold=.726; const double Tolerance=1e-5;
  internal static int Run(string[] a){if(a.Length!=5){Console.Error.WriteLine("Uso: --h1d7b2-visual-shadow <visual-model.zip> <assets.csv> <original-predictions.csv> <output>");return 2;}try{var model=Path.GetFullPath(a[1]);var assets=Path.GetFullPath(a[2]);var original=Path.GetFullPath(a[3]);var output=Path.GetFullPath(a[4]);Directory.CreateDirectory(output);var ml=new MLContext(seed:17401);DataViewSchema schema;var loaded=ml.Model.Load(model,out schema);var engine=ml.Model.CreatePredictionEngine<Input,Prediction>(loaded);if(!Reproduce(engine,assets,original,output))return 1;var before=DbState();var rows=LoadOperational();foreach(var row in rows)Score(engine,row);var after=DbState();WriteResults(output,rows,before,after);var ok=before==after;Console.WriteLine("H1D7B2 | Estado="+(ok?"APROBADO":"NO_APROBADO")+" | Operativos="+rows.Count+" | GroundTruth="+rows.Count(x=>x.GroundTruth!=null)+" | Output="+output);return ok?0:1;}catch(Exception ex){Console.Error.WriteLine("ERROR H1D7B2 | "+ex.GetType().Name+": "+ex.Message);return 1;}}
  static bool Reproduce(PredictionEngine<Input,Prediction> engine,string assets,string original,string output){var expected=ReadCsv(original,"filename","VisualProbability").ToDictionary(x=>x[0],x=>double.Parse(x[1],CultureInfo.InvariantCulture),StringComparer.OrdinalIgnoreCase);var checks=new List<string>();double max=0;int count=0;using(var p=new TextFieldParser(assets)){p.TextFieldType=FieldType.Delimited;p.HasFieldsEnclosedInQuotes=true;p.SetDelimiters(",");var h=p.ReadFields();var c=h.Select((n,i)=>new{n,i}).ToDictionary(x=>x.n,x=>x.i);while(!p.EndOfData){var f=p.ReadFields();if(f==null)continue;var name=Path.GetFileName(f[c["Path"]]);var features=f[c["VisualFeatures"]].Split(';').Select(x=>float.Parse(x,CultureInfo.InvariantCulture)).ToArray();var actual=engine.Predict(new Input{Features=features}).Probability;double old;if(!expected.TryGetValue(name,out old))throw new InvalidDataException("Falta predicción original: "+name);var delta=Math.Abs(actual-old);max=Math.Max(max,delta);count++;checks.Add(name+","+old.ToString("R",CultureInfo.InvariantCulture)+","+actual.ToString("R",CultureInfo.InvariantCulture)+","+delta.ToString("R",CultureInfo.InvariantCulture));}}var ok=count==80&&max<=Tolerance;File.WriteAllText(Path.Combine(output,"reproduction-check.md"),"# Reproducción H1D4A\n\n- Filas: "+count+"/80\n- Tolerancia: "+Tolerance.ToString("R",CultureInfo.InvariantCulture)+"\n- Delta máximo: "+max.ToString("R",CultureInfo.InvariantCulture)+"\n- Equivalente: **"+ok+"**\n- Modelo reentrenado: No. Threshold modificado: No.\n",new UTF8Encoding(false));File.WriteAllLines(Path.Combine(output,"reproduction-details.csv"),new[]{"Filename,OriginalProbability,ReproducedProbability,AbsoluteDelta"}.Concat(checks),new UTF8Encoding(false));return ok;}
  static List<Row> LoadOperational(){const string q=@"SELECT d.Id,d.Clasificacion,d.ResultadoRevision,d.EtiquetaRevision,d.RutaLocal,d.HashSha256 FROM dbo.DocumentoRecepcion d WHERE d.Clasificacion=N'FACTURA' OR d.ResultadoRevision=N'FACTURA' OR (d.Clasificacion=N'REVISAR' AND d.ResultadoRevision IS NULL) OR d.EtiquetaRevision IS NOT NULL ORDER BY d.Id;";var z=new List<Row>();using(var cn=new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))using(var cmd=new SqlCommand(q,cn)){cn.Open();using(var r=cmd.ExecuteReader())while(r.Read())z.Add(new Row{Id=r.GetInt64(0),Automatic=r.GetString(1),Result=r.IsDBNull(2)?null:r.GetString(2),Human=r.IsDBNull(3)?null:r.GetString(3),Path=r.GetString(4),Hash=r.GetString(5)});}return z;}
  static void Score(PredictionEngine<Input,Prediction> engine,Row r){var sw=Stopwatch.StartNew();var temp=Path.Combine(Path.GetTempPath(),"H1D7B2-"+Guid.NewGuid().ToString("N")+".png");try{r.Path=ResolvePhysicalPath(r);var bytes=File.ReadAllBytes(r.Path);r.Format=Format(bytes);r.Eligible=r.Format=="PDF"||r.Format=="PNG"||r.Format=="JPEG";r.GroundTruth=r.Human=="FACTURA"||r.Human=="OTRO_DOCUMENTO"?"DOCUMENTO":r.Human=="NO_DOCUMENTO"?"NO_DOCUMENTO":null;if(!r.Eligible){r.NotApplicableReason="FORMATO_FUERA_DOMINIO_H1D4A";return;}var source=r.Path;if(r.Format=="PDF"){Conversion.SavePng(temp,bytes,0,options:new RenderOptions{Dpi=150});source=temp;}var features=Normalize(source);var p=engine.Predict(new Input{Features=features});r.Probability=p.Probability;r.HasProbability=true;r.At050=r.Probability>=.5;r.At0726=r.Probability>=Threshold;r.Critical=r.GroundTruth=="DOCUMENTO"&&!r.At0726;}finally{sw.Stop();r.Duration=sw.ElapsedMilliseconds;if(File.Exists(temp))File.Delete(temp);}}
  static string ResolvePhysicalPath(Row r){if(File.Exists(r.Path)&&Hash(r.Path)==r.Hash)return r.Path;var cursor=Directory.GetParent(r.Path);while(cursor!=null&&!string.Equals(cursor.Name,"Facturas",StringComparison.OrdinalIgnoreCase)&&!string.Equals(cursor.Name,"Revisar",StringComparison.OrdinalIgnoreCase))cursor=cursor.Parent;if(cursor==null||cursor.Parent==null)throw new FileNotFoundException("Ruta operativa fuera de Facturas/Revisar para DocumentoId="+r.Id+". RutaSQL="+r.Path,r.Path);var storage=cursor.Parent.FullName;var matches=new[]{Path.Combine(storage,"Facturas"),Path.Combine(storage,"Revisar")}.Where(Directory.Exists).SelectMany(x=>Directory.EnumerateFiles(x,Path.GetFileName(r.Path),System.IO.SearchOption.AllDirectories)).Where(x=>Hash(x)==r.Hash).Distinct(StringComparer.OrdinalIgnoreCase).ToList();if(matches.Count!=1)throw new FileNotFoundException("No se pudo resolver de forma única el archivo operativo para DocumentoId="+r.Id+". RutaSQL="+r.Path+". CoincidenciasHash="+matches.Count,r.Path);return matches[0];}
  static string Hash(string path){using(var sha=SHA256.Create())using(var stream=File.OpenRead(path))return BitConverter.ToString(sha.ComputeHash(stream)).Replace("-","").ToLowerInvariant();}
  static float[] Normalize(string source){using(var input=Image.FromFile(source))using(var bitmap=new Bitmap(96,96,PixelFormat.Format24bppRgb))using(var g=Graphics.FromImage(bitmap)){g.Clear(Color.White);g.InterpolationMode=InterpolationMode.HighQualityBicubic;var scale=Math.Min(96d/input.Width,96d/input.Height);var w=Math.Max(1,(int)(input.Width*scale));var h=Math.Max(1,(int)(input.Height*scale));g.DrawImage(input,(96-w)/2,(96-h)/2,w,h);var f=new float[64];for(var y=0;y<96;y++)for(var x=0;x<96;x++){var c=bitmap.GetPixel(x,y);f[c.R/16]++;f[16+c.G/16]++;f[32+c.B/16]++;f[48+((c.R+c.G+c.B)/3)/16]++;}for(var n=0;n<64;n++)f[n]/=9216f;return f;}}
  static void WriteResults(string o,List<Row> r,string before,string after)
  {
   Func<string,string> c=x=>"\""+(x??"").Replace("\"","\"\"")+"\"";
   var lines=new List<string>{"DocumentoRecepcionId,ClasificacionAutomatica,ResultadoRevision,EtiquetaRevision,PhysicalFormat,VisualEligibility,NotApplicableReason,VisualProbabilityDocument,VisualPredictedAt050,VisualPredictedAt0726,GroundTruthVisual,CriticalError,DurationMs"};
   lines.AddRange(r.Select(x=>string.Join(",",new[]{x.Id.ToString(),x.Automatic,x.Result,x.Human,x.Format,x.Eligible?"ELIGIBLE":"NOT_APPLICABLE",x.NotApplicableReason,x.HasProbability?x.Probability.ToString("R",CultureInfo.InvariantCulture):null,x.HasProbability?(x.At050?"DOCUMENTO":"NO_DOCUMENTO"):null,x.HasProbability?(x.At0726?"DOCUMENTO":"NO_DOCUMENTO"):null,x.GroundTruth,x.HasProbability?x.Critical.ToString():null,x.Duration.ToString()}.Select(c))));
   File.WriteAllLines(Path.Combine(o,"visual-shadow-results.csv"),lines,new UTF8Encoding(false));
   var invoices=r.Where(x=>x.Automatic=="FACTURA"||x.Result=="FACTURA").ToList();var pending=r.Where(x=>x.Automatic=="REVISAR"&&x.Result==null).ToList();var human=r.Where(x=>x.GroundTruth!=null).ToList();var humanEligible=human.Where(x=>x.Eligible).ToList();var invoiceEligible=invoices.Where(x=>x.Eligible).ToList();var pendingEligible=pending.Where(x=>x.Eligible).ToList();
   File.WriteAllText(Path.Combine(o,"coverage.md"),"# Visual coverage\n\n| Subconjunto | Eligible | Total | Coverage |\n|---|---:|---:|---:|\n| Universo | "+r.Count(x=>x.Eligible)+" | "+r.Count+" | "+Coverage(r)+" |\n| Facturas efectivas | "+invoiceEligible.Count+" | "+invoices.Count+" | "+Coverage(invoices)+" |\n| Pendientes | "+pendingEligible.Count+" | "+pending.Count+" | "+Coverage(pending)+" |\n| Ground truth humano | "+humanEligible.Count+" | "+human.Count+" | "+Coverage(human)+" |\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(o,"effective-invoice-safety.md"),"# Seguridad de facturas efectivas\n\n- Total: "+invoices.Count+"; ELIGIBLE: "+invoiceEligible.Count+"; NOT_APPLICABLE: "+invoices.Count(x=>!x.Eligible)+".\n- Eligible min/mediana/max: "+Stats(invoiceEligible)+"\n- Eligible debajo de 0.726: "+invoiceEligible.Count(x=>!x.At0726)+"\n- IDs debajo: "+string.Join(", ",invoiceEligible.Where(x=>!x.At0726).Select(x=>x.Id))+"\n- NOT_APPLICABLE: "+string.Join(", ",invoices.Where(x=>!x.Eligible).Select(x=>x.Id+" ("+x.Format+")"))+"\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(o,"operational-distribution.md"),"# Distribución operativa\n\n- Pendientes total: "+pending.Count+"; ELIGIBLE: "+pendingEligible.Count+"; NOT_APPLICABLE: "+pending.Count(x=>!x.Eligible)+".\n- Eligible min/mediana/max: "+Stats(pendingEligible)+"\n- Debajo/encima de 0.726: "+pendingEligible.Count(x=>!x.At0726)+" / "+pendingEligible.Count(x=>x.At0726)+".\n- NOT_APPLICABLE: "+string.Join(", ",pending.Where(x=>!x.Eligible).Select(x=>x.Id+" ("+x.Format+")"))+"\n- Rangos bajo/intermedio/alto son descriptivos por distribución; no se definieron thresholds nuevos.\n",new UTF8Encoding(false));
   int tp=humanEligible.Count(x=>x.GroundTruth=="DOCUMENTO"&&x.At0726),fn=humanEligible.Count(x=>x.GroundTruth=="DOCUMENTO"&&!x.At0726),tn=humanEligible.Count(x=>x.GroundTruth=="NO_DOCUMENTO"&&!x.At0726),fp=humanEligible.Count(x=>x.GroundTruth=="NO_DOCUMENTO"&&x.At0726);
   File.WriteAllText(Path.Combine(o,"human-ground-truth-metrics.md"),"# Ground truth humano\n\n- Ground truth total: "+human.Count+"; ELIGIBLE: "+humanEligible.Count+"; NOT_APPLICABLE: "+human.Count(x=>!x.Eligible)+".\n- TP/TN/FP/FN a 0.726: "+tp+"/"+tn+"/"+fp+"/"+fn+"\n- Error crítico DOCUMENTO→NO_DOCUMENTO: "+fn+"\n- Sólo EtiquetaRevision se usó como verdad; NOT_APPLICABLE no entra en denominadores.\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(o,"not-applicable.md"),"# NOT_APPLICABLE\n\n| ID | Clasificación operativa | Etiqueta humana | Formato | Motivo |\n|---:|---|---|---|---|\n"+string.Join("\n",r.Where(x=>!x.Eligible).Select(x=>"| "+x.Id+" | "+(x.Result??x.Automatic)+" | "+(x.Human??"NULL")+" | "+x.Format+" | "+x.NotApplicableReason+" |"))+"\n",new UTF8Encoding(false));
   var lowInvoices=invoiceEligible.Count(x=>!x.At0726);var recommendation=humanEligible.Count==0?"NO avanzar todavía a sombra productiva continua: no existe ground truth humano elegible para medir el error crítico.":lowInvoices>0?"NO avanzar todavía a sombra productiva continua: existen facturas efectivas elegibles bajo threshold.":"Puede seguir evaluándose en sombra, sin decisiones automáticas.";
   File.WriteAllText(Path.Combine(o,"resumen.md"),"# H1D7B2 — benchmark visual en sombra\n\n**APROBADO COMO BENCHMARK; NO APROBADO PARA PRODUCCIÓN**\n\n- Universo inventariado: "+r.Count+"; ELIGIBLE: "+r.Count(x=>x.Eligible)+"; NOT_APPLICABLE: "+r.Count(x=>!x.Eligible)+".\n- SQL/cursor antes y después idénticos: "+(before==after)+"\n- Facturas elegibles bajo 0.726: "+lowInvoices+".\n- Ground truth humano: "+human.Count+"; error crítico elegible: "+fn+".\n- Recomendación: "+recommendation+"\n- NOT_APPLICABLE simula BYPASS_VISUAL hacia el flujo actual.\n- Escrituras SQL/decisiones/movimientos por score: 0. Scores en UI: No.\n",new UTF8Encoding(false));
  }
  static string Stats(List<Row> r){if(r.Count==0)return"N/A";var x=r.Select(y=>y.Probability).OrderBy(y=>y).ToList();return x.First().ToString("0.000000",CultureInfo.InvariantCulture)+" / "+x[x.Count/2].ToString("0.000000",CultureInfo.InvariantCulture)+" / "+x.Last().ToString("0.000000",CultureInfo.InvariantCulture);}
  static string Coverage(List<Row> r){return r.Count==0?"N/A":(100d*r.Count(x=>x.Eligible)/r.Count).ToString("0.00",CultureInfo.InvariantCulture)+"%";}
  static string DbState(){const string q="SELECT CONVERT(nvarchar(50),UltimoHistoryId),CONVERT(nvarchar(40),UltimaConsultaUtc,126) FROM dbo.GmailCuenta WHERE Activo=1;SELECT CHECKSUM_AGG(BINARY_CHECKSUM(Id,Clasificacion,ResultadoRevision,EtiquetaRevision,RutaLocal,HashSha256)) FROM dbo.DocumentoRecepcion;";using(var cn=new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))using(var cmd=new SqlCommand(q,cn)){cn.Open();using(var r=cmd.ExecuteReader()){r.Read();var s=(r.IsDBNull(0)?"NULL":r.GetString(0))+"|"+(r.IsDBNull(1)?"NULL":r.GetString(1));r.NextResult();r.Read();return s+"|"+(r.IsDBNull(0)?"NULL":r.GetInt32(0).ToString());}}}
  static string Format(byte[] b){if(b.Length>=5&&Encoding.ASCII.GetString(b,0,5)=="%PDF-")return"PDF";if(b.Length>=8&&b[0]==0x89&&b[1]==0x50&&b[2]==0x4e&&b[3]==0x47)return"PNG";if(b.Length>=3&&b[0]==0xff&&b[1]==0xd8&&b[2]==0xff)return"JPEG";if(b.Length>=4&&b[0]==0x50&&b[1]==0x4b)return"ZIP";return"OTRO";}
  static List<string[]> ReadCsv(string p,string a,string b){var z=new List<string[]>();using(var x=new TextFieldParser(p)){x.TextFieldType=FieldType.Delimited;x.HasFieldsEnclosedInQuotes=true;x.SetDelimiters(",");var h=x.ReadFields();var c=h.Select((n,i)=>new{n,i}).ToDictionary(y=>y.n,y=>y.i,StringComparer.OrdinalIgnoreCase);while(!x.EndOfData){var f=x.ReadFields();if(f!=null)z.Add(new[]{f[c[a]],f[c[b]]});}}return z;}
  sealed class Row{internal long Id,Duration;internal string Automatic,Result,Human,Path,Hash,Format,GroundTruth,NotApplicableReason;internal double Probability;internal bool Eligible,HasProbability,At050,At0726,Critical;}
  sealed class Input{[VectorType(64)]public float[] Features{get;set;}}
  sealed class Prediction{[ColumnName("PredictedLabel")]public bool PredictedLabel{get;set;}public float Probability{get;set;}public float Score{get;set;}}
 }
}
