using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.VisualBasic.FileIO;
using PDFtoImage;

namespace PdfRasterProbe
{
 internal static class H1D7BVisualShadowProbe
 {
  const double Threshold=.726; const double Tolerance=1e-5;
  internal static int Run(string[] a){if(a.Length!=5){Console.Error.WriteLine("Uso: --h1d7b-visual-shadow <visual-model.zip> <assets.csv> <original-predictions.csv> <output>");return 2;}try{var model=Path.GetFullPath(a[1]);var assets=Path.GetFullPath(a[2]);var original=Path.GetFullPath(a[3]);var output=Path.GetFullPath(a[4]);Directory.CreateDirectory(output);var ml=new MLContext(seed:17401);DataViewSchema schema;var loaded=ml.Model.Load(model,out schema);var engine=ml.Model.CreatePredictionEngine<Input,Prediction>(loaded);if(!Reproduce(engine,assets,original,output))return 1;var before=DbState();var rows=LoadOperational();foreach(var row in rows)Score(engine,row);var after=DbState();WriteResults(output,rows,before,after);var ok=before==after;Console.WriteLine("H1D7B | Estado="+(ok?"APROBADO":"NO_APROBADO")+" | Operativos="+rows.Count+" | GroundTruth="+rows.Count(x=>x.GroundTruth!=null)+" | Output="+output);return ok?0:1;}catch(Exception ex){Console.Error.WriteLine("ERROR H1D7B | "+ex.GetType().Name+": "+ex.Message);return 1;}}
  static bool Reproduce(PredictionEngine<Input,Prediction> engine,string assets,string original,string output){var expected=ReadCsv(original,"filename","VisualProbability").ToDictionary(x=>x[0],x=>double.Parse(x[1],CultureInfo.InvariantCulture),StringComparer.OrdinalIgnoreCase);var checks=new List<string>();double max=0;int count=0;using(var p=new TextFieldParser(assets)){p.TextFieldType=FieldType.Delimited;p.HasFieldsEnclosedInQuotes=true;p.SetDelimiters(",");var h=p.ReadFields();var c=h.Select((n,i)=>new{n,i}).ToDictionary(x=>x.n,x=>x.i);while(!p.EndOfData){var f=p.ReadFields();if(f==null)continue;var name=Path.GetFileName(f[c["Path"]]);var features=f[c["VisualFeatures"]].Split(';').Select(x=>float.Parse(x,CultureInfo.InvariantCulture)).ToArray();var actual=engine.Predict(new Input{Features=features}).Probability;double old;if(!expected.TryGetValue(name,out old))throw new InvalidDataException("Falta predicción original: "+name);var delta=Math.Abs(actual-old);max=Math.Max(max,delta);count++;checks.Add(name+","+old.ToString("R",CultureInfo.InvariantCulture)+","+actual.ToString("R",CultureInfo.InvariantCulture)+","+delta.ToString("R",CultureInfo.InvariantCulture));}}var ok=count==80&&max<=Tolerance;File.WriteAllText(Path.Combine(output,"reproduction-check.md"),"# Reproducción H1D4A\n\n- Filas: "+count+"/80\n- Tolerancia: "+Tolerance.ToString("R",CultureInfo.InvariantCulture)+"\n- Delta máximo: "+max.ToString("R",CultureInfo.InvariantCulture)+"\n- Equivalente: **"+ok+"**\n- Modelo reentrenado: No. Threshold modificado: No.\n",new UTF8Encoding(false));File.WriteAllLines(Path.Combine(output,"reproduction-details.csv"),new[]{"Filename,OriginalProbability,ReproducedProbability,AbsoluteDelta"}.Concat(checks),new UTF8Encoding(false));return ok;}
  static List<Row> LoadOperational(){const string q=@"SELECT d.Id,d.Clasificacion,d.ResultadoRevision,d.EtiquetaRevision,d.RutaLocal FROM dbo.DocumentoRecepcion d WHERE d.Clasificacion=N'FACTURA' OR d.ResultadoRevision=N'FACTURA' OR (d.Clasificacion=N'REVISAR' AND d.ResultadoRevision IS NULL) OR d.EtiquetaRevision IS NOT NULL ORDER BY d.Id;";var z=new List<Row>();using(var cn=new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))using(var cmd=new SqlCommand(q,cn)){cn.Open();using(var r=cmd.ExecuteReader())while(r.Read())z.Add(new Row{Id=r.GetInt64(0),Automatic=r.GetString(1),Result=r.IsDBNull(2)?null:r.GetString(2),Human=r.IsDBNull(3)?null:r.GetString(3),Path=r.GetString(4)});}return z;}
  static void Score(PredictionEngine<Input,Prediction> engine,Row r){var sw=Stopwatch.StartNew();var temp=Path.Combine(Path.GetTempPath(),"H1D7B-"+Guid.NewGuid().ToString("N")+".png");try{var bytes=File.ReadAllBytes(r.Path);r.Format=Format(bytes);var source=r.Path;if(r.Format=="PDF"){Conversion.SavePng(temp,bytes,0,options:new RenderOptions{Dpi=150});source=temp;}var features=Normalize(source);var p=engine.Predict(new Input{Features=features});r.Probability=p.Probability;r.At050=r.Probability>=.5;r.At0726=r.Probability>=Threshold;r.GroundTruth=r.Human=="FACTURA"||r.Human=="OTRO_DOCUMENTO"?"DOCUMENTO":r.Human=="NO_DOCUMENTO"?"NO_DOCUMENTO":null;r.Critical=r.GroundTruth=="DOCUMENTO"&&!r.At0726;}finally{sw.Stop();r.Duration=sw.ElapsedMilliseconds;if(File.Exists(temp))File.Delete(temp);}}
  static float[] Normalize(string source){using(var input=Image.FromFile(source))using(var bitmap=new Bitmap(96,96,PixelFormat.Format24bppRgb))using(var g=Graphics.FromImage(bitmap)){g.Clear(Color.White);g.InterpolationMode=InterpolationMode.HighQualityBicubic;var scale=Math.Min(96d/input.Width,96d/input.Height);var w=Math.Max(1,(int)(input.Width*scale));var h=Math.Max(1,(int)(input.Height*scale));g.DrawImage(input,(96-w)/2,(96-h)/2,w,h);var f=new float[64];for(var y=0;y<96;y++)for(var x=0;x<96;x++){var c=bitmap.GetPixel(x,y);f[c.R/16]++;f[16+c.G/16]++;f[32+c.B/16]++;f[48+((c.R+c.G+c.B)/3)/16]++;}for(var n=0;n<64;n++)f[n]/=9216f;return f;}}
  static void WriteResults(string o,List<Row> r,string before,string after)
  {
   Func<string,string> c=x=>"\""+(x??"").Replace("\"","\"\"")+"\"";
   var lines=new List<string>{"DocumentoRecepcionId,ClasificacionAutomatica,ResultadoRevision,EtiquetaRevision,PhysicalFormat,VisualProbabilityDocument,VisualPredictedAt050,VisualPredictedAt0726,GroundTruthVisual,CriticalError,DurationMs"};
   lines.AddRange(r.Select(x=>string.Join(",",new[]{x.Id.ToString(),x.Automatic,x.Result,x.Human,x.Format,x.Probability.ToString("R",CultureInfo.InvariantCulture),x.At050?"DOCUMENTO":"NO_DOCUMENTO",x.At0726?"DOCUMENTO":"NO_DOCUMENTO",x.GroundTruth,x.Critical.ToString(),x.Duration.ToString()}.Select(c))));
   File.WriteAllLines(Path.Combine(o,"visual-shadow-results.csv"),lines,new UTF8Encoding(false));
   var invoices=r.Where(x=>x.Automatic=="FACTURA"||x.Result=="FACTURA").ToList();var pending=r.Where(x=>x.Automatic=="REVISAR"&&x.Result==null).ToList();var human=r.Where(x=>x.GroundTruth!=null).ToList();
   File.WriteAllText(Path.Combine(o,"effective-invoice-safety.md"),"# Seguridad de facturas efectivas\n\n- Cantidad: "+invoices.Count+"\n- Min/mediana/max: "+Stats(invoices)+"\n- Debajo de 0.726: "+invoices.Count(x=>!x.At0726)+"\n- IDs: "+string.Join(", ",invoices.Where(x=>!x.At0726).Select(x=>x.Id))+"\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(o,"operational-distribution.md"),"# Distribución operativa\n\n- Pendientes: "+pending.Count+"\n- Min/mediana/max: "+Stats(pending)+"\n- Referencia congelada 0.726: debajo="+pending.Count(x=>!x.At0726)+", encima="+pending.Count(x=>x.At0726)+".\n- Rangos diagnósticos por terciles observados: bajo/intermedio/alto; no son thresholds productivos.\n",new UTF8Encoding(false));
   int tp=human.Count(x=>x.GroundTruth=="DOCUMENTO"&&x.At0726),fn=human.Count(x=>x.GroundTruth=="DOCUMENTO"&&!x.At0726),tn=human.Count(x=>x.GroundTruth=="NO_DOCUMENTO"&&!x.At0726),fp=human.Count(x=>x.GroundTruth=="NO_DOCUMENTO"&&x.At0726);
   File.WriteAllText(Path.Combine(o,"human-ground-truth-metrics.md"),"# Ground truth humano\n\n- Etiquetados evaluables con archivo físico: "+human.Count+"\n- TP/TN/FP/FN a 0.726: "+tp+"/"+tn+"/"+fp+"/"+fn+"\n- Error crítico DOCUMENTO→NO_DOCUMENTO: "+fn+"\n- Sólo EtiquetaRevision se usó como verdad.\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(o,"resumen.md"),"# H1D7B — benchmark visual en sombra\n\n- Universo físico puntuado: "+r.Count+"\n- SQL/cursor antes y después idénticos: "+(before==after)+"\n- Modelo: H1D4A congelado; threshold histórico: 0.726.\n- Escrituras SQL/decisiones/movimientos por score: 0.\n- Scores expuestos en UI: No.\n",new UTF8Encoding(false));
  }
  static string Stats(List<Row> r){if(r.Count==0)return"N/A";var x=r.Select(y=>y.Probability).OrderBy(y=>y).ToList();return x.First().ToString("0.000000",CultureInfo.InvariantCulture)+" / "+x[x.Count/2].ToString("0.000000",CultureInfo.InvariantCulture)+" / "+x.Last().ToString("0.000000",CultureInfo.InvariantCulture);}
  static string DbState(){const string q="SELECT CONVERT(nvarchar(50),UltimoHistoryId),CONVERT(nvarchar(40),UltimaConsultaUtc,126) FROM dbo.GmailCuenta WHERE Activo=1;SELECT CHECKSUM_AGG(BINARY_CHECKSUM(Id,Clasificacion,ResultadoRevision,EtiquetaRevision,RutaLocal,HashSha256)) FROM dbo.DocumentoRecepcion;";using(var cn=new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))using(var cmd=new SqlCommand(q,cn)){cn.Open();using(var r=cmd.ExecuteReader()){r.Read();var s=(r.IsDBNull(0)?"NULL":r.GetString(0))+"|"+(r.IsDBNull(1)?"NULL":r.GetString(1));r.NextResult();r.Read();return s+"|"+(r.IsDBNull(0)?"NULL":r.GetInt32(0).ToString());}}}
  static string Format(byte[] b){if(b.Length>=5&&Encoding.ASCII.GetString(b,0,5)=="%PDF-")return"PDF";if(b.Length>=8&&b[0]==0x89&&b[1]==0x50&&b[2]==0x4e&&b[3]==0x47)return"PNG";if(b.Length>=3&&b[0]==0xff&&b[1]==0xd8&&b[2]==0xff)return"JPEG";throw new InvalidDataException("Formato no soportado.");}
  static List<string[]> ReadCsv(string p,string a,string b){var z=new List<string[]>();using(var x=new TextFieldParser(p)){x.TextFieldType=FieldType.Delimited;x.HasFieldsEnclosedInQuotes=true;x.SetDelimiters(",");var h=x.ReadFields();var c=h.Select((n,i)=>new{n,i}).ToDictionary(y=>y.n,y=>y.i,StringComparer.OrdinalIgnoreCase);while(!x.EndOfData){var f=x.ReadFields();if(f!=null)z.Add(new[]{f[c[a]],f[c[b]]});}}return z;}
  sealed class Row{internal long Id,Duration;internal string Automatic,Result,Human,Path,Format,GroundTruth;internal double Probability;internal bool At050,At0726,Critical;}
  sealed class Input{[VectorType(64)]public float[] Features{get;set;}}
  sealed class Prediction{[ColumnName("PredictedLabel")]public bool PredictedLabel{get;set;}public float Probability{get;set;}public float Score{get;set;}}
 }
}
