using System;using System.Collections.Generic;using System.Configuration;using System.Data;using System.Data.SqlClient;using System.IO;using System.Linq;using System.Security.Cryptography;using System.Text;using System.Threading.Tasks;
using RecepcionDocumental.Configuration;using RecepcionDocumental.Infrastructure;using RecepcionDocumental.Services;
namespace PdfRasterProbe{
internal static class H1D7C1GroundTruthProbe{
 internal static int Run(string[] a){if(a.Length!=3){Console.Error.WriteLine("Uso: --h1d7c1-ground-truth <RecepcionDocumental.ini> <output>");return 2;}var setup=new AppDomainSetup{ApplicationBase=AppDomain.CurrentDomain.BaseDirectory,ConfigurationFile=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(a[1])),"Web.config")};var d=AppDomain.CreateDomain("H1D7C1-WebConfig",null,setup);try{return d.ExecuteAssembly(typeof(H1D7C1GroundTruthProbe).Assembly.Location,new[]{"--h1d7c1-ground-truth-inner",a[1],a[2]});}finally{AppDomain.Unload(d);}}
 internal static int RunInner(string[] a){var output=Path.GetFullPath(a[2]);Directory.CreateDirectory(output);var cfg=ConfiguracionIni.Cargar(a[1]);cfg.PrepararRutasOperativas();ConfiguracionSistema.Inicializar(cfg);Logs.Inicializar(cfg);var run=Guid.NewGuid().ToString("N");var root=Path.Combine(cfg.RutaRevisar,"H1D7C1-"+run);Directory.CreateDirectory(root);var ids=new List<long>();var messages=new List<long>();var rows=new List<Row>();string cursorBefore=Cursor();bool atomic=false,concurrency=false,shadow=true,files=true,idempotent=true,concurrentPhysical=false,preexistingSafe=false;var orphanFiles=0;try{
  var fa=Create("A",new byte[]{1,2,3,4,5},root,run,ids,messages);var fb=Create("B",new byte[]{6,7,8,9},root,run,ids,messages);var fc=Create("C",new byte[]{10,11,12},root,run,ids,messages);var fe=Create("E",new byte[]{13,14,15,16},root,run,ids,messages);var fp=Create("P",new byte[]{20,21,22,23},root,run,ids,messages);var fx=Create("X",new byte[]{17,18,19},root,run,ids,messages);
  var shadowId=AddShadow(fe.Id);var ra=DocumentReviewService.ConfirmInvoice(fa.Id,"h1d7c1-user","factura controlada");var rb=DocumentReviewService.DiscardOtherDocument(fb.Id,"h1d7c1-user","otro controlado");var rc=DocumentReviewService.DiscardNonDocument(fc.Id,"h1d7c1-user","no documento controlado");
  var again=new[]{DocumentReviewService.ConfirmInvoice(fa.Id,"x","x"),DocumentReviewService.DiscardOtherDocument(fb.Id,"x","x"),DocumentReviewService.DiscardNonDocument(fc.Id,"x","x")};idempotent=again.All(x=>!x.Success);
  var tasks=new[]{Task.Run(()=>DocumentReviewService.ConfirmInvoice(fe.Id,"race-a","race")),Task.Run(()=>DocumentReviewService.DiscardNonDocument(fe.Id,"race-b","race"))};Task.WaitAll(tasks);concurrency=tasks.Count(x=>x.Result.Success)==1;
  var preexisting=DocumentStorage.Save(fp.Path,"FACTURA",DateTime.UtcNow,"h1d7c1-"+run+"-P","P.bin",fp.Hash);var preTasks=new[]{Task.Run(()=>DocumentReviewService.ConfirmInvoice(fp.Id,"pre-a","preexisting")),Task.Run(()=>DocumentReviewService.DiscardNonDocument(fp.Id,"pre-b","preexisting"))};Task.WaitAll(preTasks);preexistingSafe=File.Exists(preexisting.FullPath)&&preTasks.Count(x=>x.Result.Success)==1;
  AddAtomicConstraint(fx.Hash);try{DocumentReviewService.DiscardNonDocument(fx.Id,"atomic","atomic");}catch(SqlException){}finally{DropAtomicConstraint();}var sx=Read(fx.Id);atomic=sx.Result==null&&sx.Label==null&&sx.GtCount==0;
  foreach(var f in new[]{fa,fb,fc,fe,fp,fx}){var s=Read(f.Id);s.Name=f.Name;s.OriginalPath=f.Path;s.ExpectedHash=f.Hash;s.ExpectedSize=f.Size;rows.Add(s);}var arow=rows[0];var brow=rows[1];var crow=rows[2];var erow=rows[3];var prow=rows[4];
  files=File.Exists(arow.Path)&&Hash(arow.Path)==fa.Hash&&new FileInfo(arow.Path).Length==fa.Size&&!File.Exists(fa.Path)&&File.Exists(fb.Path)&&Hash(fb.Path)==fb.Hash&&File.Exists(fc.Path)&&Hash(fc.Path)==fc.Hash;
  shadow=erow.ShadowId==shadowId&&brow.ShadowId==null;
  var eInvoices=InvoiceFiles(cfg.RutaFacturas,run,"E",fe.Hash);var pInvoices=InvoiceFiles(cfg.RutaFacturas,run,"P",fp.Hash);concurrentPhysical=erow.Result=="FACTURA"?eInvoices.Count==1&&!File.Exists(fe.Path):eInvoices.Count==0&&File.Exists(fe.Path);preexistingSafe=preexistingSafe&&pInvoices.Count==1&&(prow.Result=="FACTURA"?!File.Exists(fp.Path):File.Exists(fp.Path));orphanFiles=(erow.Result=="FACTURA"?Math.Max(0,eInvoices.Count-1):eInvoices.Count)+Math.Max(0,pInvoices.Count-1);
  var labels=ra.Success&&rb.Success&&rc.Success&&arow.Result=="FACTURA"&&arow.Binary=="FACTURA"&&arow.Detail=="FACTURA"&&brow.Result=="DESCARTAR"&&brow.Binary=="NO_FACTURA"&&brow.Detail=="OTRO_DOCUMENTO"&&crow.Result=="DESCARTAR"&&crow.Binary=="NO_FACTURA"&&crow.Detail=="NO_DOCUMENTO";
  var single=rows.Take(5).All(x=>x.GtCount==1&&x.Sequence==1&&x.Current&&x.Source=="REVISION_OPERATIVA"&&x.Hash==x.ExpectedHash&&x.Size==x.ExpectedSize);
  var gmail=Cursor()==cursorBefore;var ok=labels&&single&&files&&idempotent&&concurrency&&concurrentPhysical&&preexistingSafe&&orphanFiles==0&&atomic&&shadow&&gmail;
  Write(output,rows,ok,files,idempotent,concurrency,atomic,shadow,gmail,concurrentPhysical,preexistingSafe,orphanFiles);Console.WriteLine("H1D7C1 | Labels="+labels+" | Files="+files+" | Idempotent="+idempotent+" | Concurrency="+concurrency+" | ConcurrentPhysical="+concurrentPhysical+" | PreexistingSafe="+preexistingSafe+" | Atomic="+atomic+" | ShadowOptional="+shadow+" | Gmail="+gmail+" | OrphanInvoiceFiles="+orphanFiles+" | Gate="+ok);return ok?0:1;
 }finally{try{DropAtomicConstraint();}catch{}Cleanup(ids,messages);foreach(var p in RunInvoiceFiles(cfg.RutaFacturas,run))try{File.Delete(p);}catch{}try{if(Directory.Exists(root))Directory.Delete(root,true);}catch{}}}
 static Fixture Create(string name,byte[] bytes,string root,string run,List<long> ids,List<long> messages){var path=Path.Combine(root,name+".bin");File.WriteAllBytes(path,bytes);var hash=Hash(path);const string q=@"DECLARE @a INT=(SELECT TOP(1) Id FROM dbo.GmailCuenta ORDER BY Activo DESC,Id);INSERT dbo.GmailMensaje(GmailCuentaId,GmailMessageId,FechaMensajeUtc,Remitente,Asunto) OUTPUT inserted.Id VALUES(@a,@gm,SYSUTCDATETIME(),N'h1d7c1@local',N'fixture');DECLARE @m BIGINT=SCOPE_IDENTITY();INSERT dbo.DocumentoRecepcion(GmailMensajeId,GmailPartId,OrigenTipo,OrigenHash,NombreOriginal,MimeType,TamanioBytes,RutaLocal,HashSha256,Clasificacion,MetodoDeteccion,Confianza,MotivoClasificacion,QrDetectado,FechaClasificacionUtc) OUTPUT inserted.Id VALUES(@m,@part,N'DIRECTO',@hash,@name,N'application/octet-stream',@size,@path,@hash,N'REVISAR',N'H1D7C1_FIXTURE',NULL,N'fixture',0,SYSUTCDATETIME());";using(var cn=Cn())using(var cmd=new SqlCommand(q,cn)){cmd.Parameters.AddWithValue("@gm","h1d7c1-"+run+"-"+name);cmd.Parameters.AddWithValue("@part",name);cmd.Parameters.AddWithValue("@hash",hash);cmd.Parameters.AddWithValue("@name",name+".bin");cmd.Parameters.AddWithValue("@size",bytes.LongLength);cmd.Parameters.AddWithValue("@path",path);cn.Open();using(var r=cmd.ExecuteReader()){r.Read();var mid=r.GetInt64(0);r.NextResult();r.Read();var id=r.GetInt64(0);messages.Add(mid);ids.Add(id);return new Fixture{Name=name,Id=id,Path=path,Hash=hash,Size=bytes.LongLength};}}}
 static long AddShadow(long id){const string q=@"INSERT dbo.DocumentoVisionShadow(DocumentoRecepcionId,ModeloVersion,ModeloSha256,PreprocesamientoVersion,Estado,PNoFactura,PFactura,Zona,OrigenVisual,RasterReutilizado,FechaEvaluacionUtc) OUTPUT inserted.Id VALUES(@id,N'H1D7C1-FIXTURE',REPLICATE('A',64),N'FIXTURE',N'OK',.01,.99,N'FACTURA_FUERTE',N'FIXTURE',0,SYSUTCDATETIME());";using(var cn=Cn())using(var cmd=new SqlCommand(q,cn)){cmd.Parameters.AddWithValue("@id",id);cn.Open();return Convert.ToInt64(cmd.ExecuteScalar());}}
 static Row Read(long id){const string q=@"SELECT d.ResultadoRevision,d.EtiquetaRevision,d.RutaLocal,gt.EtiquetaBinaria,gt.EtiquetaDetallada,gt.Fuente,gt.Secuencia,gt.EsVigente,gt.DocumentoSha256,gt.TamanioBytes,gt.DocumentoVisionShadowId,(SELECT COUNT(*) FROM dbo.DocumentoGroundTruth x WHERE x.DocumentoRecepcionId=d.Id) FROM dbo.DocumentoRecepcion d LEFT JOIN dbo.DocumentoGroundTruth gt ON gt.DocumentoRecepcionId=d.Id AND gt.EsVigente=1 WHERE d.Id=@id;";using(var cn=Cn())using(var cmd=new SqlCommand(q,cn)){cmd.Parameters.AddWithValue("@id",id);cn.Open();using(var r=cmd.ExecuteReader()){r.Read();return new Row{Id=id,Result=S(r,0),Label=S(r,1),Path=S(r,2),Binary=S(r,3),Detail=S(r,4),Source=S(r,5),Sequence=r.IsDBNull(6)?0:r.GetInt32(6),Current=!r.IsDBNull(7)&&r.GetBoolean(7),Hash=S(r,8),Size=r.IsDBNull(9)?0:r.GetInt64(9),ShadowId=r.IsDBNull(10)?(long?)null:r.GetInt64(10),GtCount=r.GetInt32(11)};}}}
 static void AddAtomicConstraint(string hash){Exec("SET ARITHABORT ON;ALTER TABLE dbo.DocumentoGroundTruth ADD CONSTRAINT CK_H1D7C1_AtomicProbe CHECK(DocumentoSha256<>N'"+hash+"');");}static void DropAtomicConstraint(){Exec("SET ARITHABORT ON;IF EXISTS(SELECT 1 FROM sys.check_constraints WHERE name=N'CK_H1D7C1_AtomicProbe') ALTER TABLE dbo.DocumentoGroundTruth DROP CONSTRAINT CK_H1D7C1_AtomicProbe;");}
 static void Exec(string q){using(var cn=Cn())using(var cmd=new SqlCommand(q,cn)){cn.Open();cmd.ExecuteNonQuery();}}static SqlConnection Cn(){return new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);}static string S(SqlDataReader r,int i){return r.IsDBNull(i)?null:r.GetString(i);}static string Hash(string p){using(var x=SHA256.Create())using(var f=File.OpenRead(p))return BitConverter.ToString(x.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
 static string Cursor(){using(var cn=Cn())using(var cmd=new SqlCommand("SELECT ISNULL(CONVERT(nvarchar(50),UltimoHistoryId),N'<NULL>')+N'|'+ISNULL(CONVERT(nvarchar(40),UltimaConsultaUtc,126),N'<NULL>') FROM dbo.GmailCuenta WHERE Activo=1;",cn)){cn.Open();return Convert.ToString(cmd.ExecuteScalar());}}
 static List<string> RunInvoiceFiles(string root,string run){return Directory.Exists(root)?Directory.GetFiles(root,"*",SearchOption.AllDirectories).Where(x=>x.IndexOf("h1d7c1-"+run,StringComparison.OrdinalIgnoreCase)>=0).ToList():new List<string>();}
 static List<string> InvoiceFiles(string root,string run,string name,string hash){var suffix=name+"_"+hash.Substring(0,12)+".bin";return RunInvoiceFiles(root,run).Where(x=>string.Equals(Path.GetFileName(x),suffix,StringComparison.OrdinalIgnoreCase)).ToList();}
 static void Cleanup(List<long> ids,List<long> msgs){if(ids.Count==0)return;using(var cn=Cn())using(var cmd=new SqlCommand("DELETE dbo.DocumentoGroundTruth WHERE DocumentoRecepcionId IN ("+string.Join(",",ids)+");DELETE dbo.DocumentoVisionShadow WHERE DocumentoRecepcionId IN ("+string.Join(",",ids)+");DELETE dbo.DocumentoRecepcion WHERE Id IN ("+string.Join(",",ids)+");DELETE dbo.GmailMensaje WHERE Id IN ("+string.Join(",",msgs)+");",cn)){cn.Open();cmd.ExecuteNonQuery();}}
 static void Write(string o,List<Row> r,bool ok,bool files,bool idem,bool conc,bool atomic,bool shadow,bool gmail,bool physical,bool preexisting,int orphans){File.WriteAllLines(Path.Combine(o,"ground-truth.csv"),new[]{"Name,Id,Result,Label,Binary,Detail,Source,Sequence,Current,GroundTruthCount,ShadowId"}.Concat(r.Select(x=>string.Join(",",x.Name,x.Id,x.Result,x.Label,x.Binary,x.Detail,x.Source,x.Sequence,x.Current,x.GtCount,x.ShadowId))).ToArray(),new UTF8Encoding(false));File.WriteAllText(Path.Combine(o,"file-evidence.md"),"# Evidencia física\n\n- Contrato FACTURA y limpieza posterior: "+files+".\n- Archivos NO_FACTURA preservados con hash/tamaño: "+files+".\n- Consistencia física concurrente: "+physical+".\n- Destino preexistente preservado: "+preexisting+".\n- OrphanInvoiceFiles="+orphans+".\n",new UTF8Encoding(false));File.WriteAllText(Path.Combine(o,"concurrency.md"),"# Concurrencia\n\n- Reintentos rechazados: "+idem+".\n- Exactamente un ganador concurrente: "+conc+".\n- FACTURA vs NO_DOCUMENTO físicamente consistente: "+physical+".\n- Archivo preexistente no borrado: "+preexisting+".\n- OrphanInvoiceFiles="+orphans+".\n- Rollback UPDATE + ground truth ante fallo: "+atomic+".\n",new UTF8Encoding(false));File.WriteAllText(Path.Combine(o,"sql-before-after.md"),"# SQL antes/después\n\n- Fixtures controlados: "+r.Count+".\n- Gmail/cursor sin cambios: "+gmail+".\n- Fixtures eliminados al finalizar.\n",new UTF8Encoding(false));File.WriteAllText(Path.Combine(o,"backfill.md"),"# Backfill\n\n- Elegibles: 0.\n- Insertados: 0.\n- Históricos no migrables por EtiquetaRevision NULL: 2.\n- No se infirieron etiquetas.\n",new UTF8Encoding(false));File.WriteAllText(Path.Combine(o,"resumen.md"),"# H1D7C1\n\n**H1D7C1 "+(ok?"APROBADO":"NO APROBADO")+"**\n\n- Shadow opcional y sin autoridad: "+shadow+".\n- ConcurrentPhysical="+physical+".\n- OrphanInvoiceFiles="+orphans+".\n- Gate operativo: "+ok+".\n",new UTF8Encoding(false));}
 sealed class Fixture{internal string Name,Path,Hash;internal long Id,Size;}sealed class Row{internal string Name,Result,Label,Path,Binary,Detail,Source,Hash,ExpectedHash,OriginalPath;internal long Id,Size,ExpectedSize;internal int Sequence,GtCount;internal bool Current;internal long? ShadowId;}
}}
