using System;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using RecepcionDocumental.Configuration;
using RecepcionDocumental.Infrastructure;
using RecepcionDocumental.Services;
namespace PdfRasterProbe
{
 internal static class H1D7AReviewValidationProbe
 {
  internal static int Run(string[] a){if(a.Length!=5)return 2;var setup=new AppDomainSetup{ApplicationBase=AppDomain.CurrentDomain.BaseDirectory,ConfigurationFile=Path.Combine(Path.GetDirectoryName(Path.GetFullPath(a[1])),"Web.config")};var d=AppDomain.CreateDomain("H1D7A-WebConfig",null,setup);try{return d.ExecuteAssembly(typeof(H1D7AReviewValidationProbe).Assembly.Location,new[]{"--h1d7a-review-inner",a[1],a[2],a[3],a[4]});}finally{AppDomain.Unload(d);}}
  internal static int RunInner(string[] a){var output=Path.GetFullPath(a[4]);Directory.CreateDirectory(output);long invoice=long.Parse(a[2]),discard=long.Parse(a[3]);var c=ConfiguracionIni.Cargar(a[1]);c.PrepararRutasOperativas();ConfiguracionSistema.Inicializar(c);Logs.Inicializar(c);var before=Snap(invoice,discard);var resumed=before.AResult=="FACTURA"&&before.BResult=="DESCARTAR";DocumentReviewResult firstA=null,firstB=null;if(!resumed){firstA=DocumentReviewService.ConfirmInvoice(invoice,null,"H1D7A validación controlada: factura H1D6A2");firstB=DocumentReviewService.Discard(discard,null,"H1D7A validación controlada: ruido FlightAware");}var secondA=DocumentReviewService.ConfirmInvoice(invoice,null,"reintento idempotencia");var secondB=DocumentReviewService.Discard(discard,null,"reintento idempotencia");var after=Snap(invoice,discard);var physicalInvoice=File.Exists(after.APath)&&Hash(after.APath)==after.AHash;var discardGone=!File.Exists(after.BPath);var deltasOk=resumed?(after.Facturas==before.Facturas&&after.Pendientes==before.Pendientes):(firstA.Success&&firstB.Success&&after.Facturas==before.Facturas+1&&after.Pendientes==before.Pendientes-2);var ok=!secondA.Success&&!secondB.Success&&after.AResult=="FACTURA"&&after.BResult=="DESCARTAR"&&after.AClass=="REVISAR"&&after.BClass=="REVISAR"&&physicalInvoice&&discardGone&&deltasOk&&after.History==before.History&&after.LastQuery==before.LastQuery;
   File.WriteAllText(Path.Combine(output,"sql-before-after.md"),"# H1D7A SQL antes/después\n\n|Dato|Antes|Después|\n|---|---|---|\n|Facturas efectivas|"+before.Facturas+"|"+after.Facturas+"|\n|Pendientes|"+before.Pendientes+"|"+after.Pendientes+"|\n|10079 Clasificación automática|"+before.AClass+"|"+after.AClass+"|\n|10079 ResultadoRevision|"+before.AResult+"|"+after.AResult+"|\n|10079 FechaRevisionUtc|"+before.ARevision+"|"+after.ARevision+"|\n|10079 UsuarioRevision|NULL|NULL|\n|10079 Observación|H1D7A validación controlada: factura H1D6A2|sin cambios|\n|10116 Clasificación automática|"+before.BClass+"|"+after.BClass+"|\n|10116 ResultadoRevision|"+before.BResult+"|"+after.BResult+"|\n|10116 FechaRevisionUtc|"+before.BRevision+"|"+after.BRevision+"|\n|10116 UsuarioRevision|NULL|NULL|\n|10116 Observación|H1D7A validación controlada: ruido FlightAware|sin cambios|\n|UltimoHistoryId|"+before.History+"|"+after.History+"|\n|UltimaConsultaUtc|"+before.LastQuery.ToString("O")+"|"+after.LastQuery.ToString("O")+"|\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(output,"file-evidence.md"),"# Evidencia física\n\n- FACTURA nueva: `"+after.APath+"`\n- Hash: `"+after.AHash+"`\n- Copia verificada: "+physicalInvoice+"\n- Archivo descartado eliminado: "+discardGone+"\n",new UTF8Encoding(false));
   File.WriteAllText(Path.Combine(output,"resumen.md"),"# H1D7A — Validación controlada\n\n**"+(ok?"APROBADO":"NO APROBADO")+"**\n\n- Ejecución retomada tras fallo del arnés posterior a ambas decisiones: "+resumed+".\n- REVISAR→FACTURA persistido: "+(after.AResult=="FACTURA")+"; reintento rechazado: "+(!secondA.Success)+".\n- REVISAR→DESCARTAR persistido: "+(after.BResult=="DESCARTAR")+"; reintento rechazado: "+(!secondB.Success)+".\n- Clasificaciones automáticas preservadas: "+(after.AClass=="REVISAR"&&after.BClass=="REVISAR")+".\n- UsuarioRevision: NULL (sin identidad humana autenticada en el probe).\n- Gmail/cursor sin cambios durante reintentos: "+(after.History==before.History&&after.LastQuery==before.LastQuery)+".\n",new UTF8Encoding(false));Console.WriteLine("H1D7A | Estado="+(ok?"APROBADO":"NO_APROBADO")+" | Output="+output);return ok?0:1;}
  static S Snap(long a,long b){const string q=@"SELECT UltimoHistoryId,UltimaConsultaUtc FROM dbo.GmailCuenta WHERE Activo=1;SELECT SUM(CASE WHEN Clasificacion=N'FACTURA' OR ResultadoRevision=N'FACTURA' THEN 1 ELSE 0 END),SUM(CASE WHEN Clasificacion=N'REVISAR' AND ResultadoRevision IS NULL THEN 1 ELSE 0 END) FROM dbo.DocumentoRecepcion;SELECT Id,Clasificacion,ResultadoRevision,RutaLocal,HashSha256,FechaRevisionUtc FROM dbo.DocumentoRecepcion WHERE Id IN (@A,@B) ORDER BY Id;";var s=new S();using(var cn=new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))using(var cmd=new SqlCommand(q,cn)){cmd.Parameters.AddWithValue("@A",a);cmd.Parameters.AddWithValue("@B",b);cn.Open();using(var r=cmd.ExecuteReader()){r.Read();s.History=r.IsDBNull(0)?null:r.GetString(0);s.LastQuery=r.GetDateTime(1);r.NextResult();r.Read();s.Facturas=Convert.ToInt32(r.GetValue(0));s.Pendientes=Convert.ToInt32(r.GetValue(1));r.NextResult();while(r.Read()){var isA=r.GetInt64(0)==a;if(isA){s.AClass=r.GetString(1);s.AResult=r.IsDBNull(2)?null:r.GetString(2);s.APath=r.GetString(3);s.AHash=r.GetString(4);s.ARevision=r.IsDBNull(5)?"NULL":r.GetDateTime(5).ToString("O");}else{s.BClass=r.GetString(1);s.BResult=r.IsDBNull(2)?null:r.GetString(2);s.BPath=r.GetString(3);s.BHash=r.GetString(4);s.BRevision=r.IsDBNull(5)?"NULL":r.GetDateTime(5).ToString("O");}}}}return s;}
  static string Hash(string p){using(var x=SHA256.Create())using(var f=File.OpenRead(p))return BitConverter.ToString(x.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
  sealed class S{internal string History,AClass,AResult,APath,AHash,ARevision,BClass,BResult,BPath,BHash,BRevision;internal DateTime LastQuery;internal int Facturas,Pendientes;}
 }
}
